### PR TITLE
Add mating to EarthMC

### PR DESCRIPTION
**Pull request by 3meraldK**
:trollface: because many players wanted it so why not.

### CODE REVIEW

**Comment by 3meraldK** [comment]
why did you close it @DasCodes its not a joke

**Comment by Kieubasiarz** [comment]
This actually works, has a reasonable cooldown, a would be a fun gimmick. Worry about lag?

**Comment by 3meraldK** [comment]
> This actually works, has a reasonable cooldown, a would be a fun gimmick. Worry about lag?

it creates no lag at all because of the code,
+ also it would be a easter egg x)

**Comment by DasCodes** [comment]
> why did you close it @DasCodes its not a joke

Exactly.

**Pull request closed without merging**
